### ISSUE TITLE
Prior art

### ISSUE THREAD

**Issue by odanoburu** [rougier/persid#1]
Just in case you don't know it: https://github.com/cpitclaudel/biblio.el
If you do, do close the issue, but a comparison might be useful for prospective users!

org-ref also has some similar-looking code, but also lots of unrelated functionality.

**Comment by rougier** [comment]
Oh many thanks for the link that I didn't know. I definetely need to test it. I'm aware of org-ref but all the stuf related to get bibtex is spread over many files and it's not really convenient when you only need the bibtex part.

**Comment by yantar92** [comment]
I also have partial implementation in https://github.com/yantar92/org-capture-ref

**Comment by rougier** [comment]
Thanks, I've just added the link in the README. In the end, I realized there are several libraries around that do what I intended to do in the first place. I didn't search enough :)

**Comment by orgtre** [comment]
There is also [Zotra](https://github.com/mpedramfar/zotra) (and [biblio-zotero](https://github.com/gkowzan/biblio-zotero)) which uses the full power of the over 600 [Zotero translators](https://www.zotero.org/support/translators). It works both with urls (`zotra-add-entry-from-url`) and identifiers (DOI, ISBN, PMID, arXiv ID; `zotra-add-entry-from-search`). Plus one can choose among a multitude of output formats via `zotra-default-entry-format` (bibtex, biblatex, csljson, etc.).

**Comment by rougier** [comment]
Thanks, I just update the README

**Comment by nicolas-graves** [comment]
You could also add https://github.com/emacs-citar/citar ;) @rougier

**Comment by rougier** [comment]
Done!
